# steps are as follows
# 1. Check out the code
# 2. Set up docker
# 3. Login to docker hub
# 4. Tag image w latest commit
# 5. Build and push image to docker hub

name: Build and publish docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract git hash to tag image
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aviral2806/todoapp:${{ env.commit_hash }}
